Sapper/Sapper/Models/GameSettings.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using Sapper.SapperEngine.MaskedFigure;

namespace Sapper.Models
{
    public class GameSettings : IValidatableObject
    {
        private readonly SelectListItem[] _figuresName =
        {
            new SelectListItem
            {
                Value = ((int) FigureType.Quadro).ToString(),
                Text = "Quadro"
            },
            new SelectListItem
            {
                Value = ((int) FigureType.Romb).ToString(),
                Text = "Romb"
            },
            new SelectListItem
            {
                Value = ((int) FigureType.Star).ToString(),
                Text = "Star"
            },
            new SelectListItem
            {
                Value = ((int) FigureType.Triangle).ToString(),
                Text = "Triangle"
            }
        };

        private const int _maxHeigth = 50;
        private const int _maxWidth = 50;

        public int Width { get; set; }

        public int Height { get; set; }

        public int MineNumber { get; set; }

        public bool IsTimeLimit
        {
            get { return TimeLimit.Ticks > 0; }
        }

        public TimeSpan TimeLimit { get; set; }

        public FigureType SelectedFigure { get; set; }

        public IEnumerable<SelectListItem> FigureList
        {
            get { return _figuresName; }
        }


        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            bool isError = false;

            try
            {
                int w = Width;
                int h = Height;
                int m = MineNumber;

                if (w < 3 || w > _maxWidth)
                    isError = true;

                if (h < 3 || h > _maxHeigth)
                    isError = true;

                if (m < 1 || m > w*h)
                    isError = true;
            }
            catch
            {
                isError = true;
            }

            if (isError)
                yield return new ValidationResult("Invalid settings!", new[] {"Error"});
        }
    }
}

Sapper/Sapper/Controllers/GameController.cs
using System;
using System.Web.Mvc;
using Newtonsoft.Json;
using Sapper.JsonModels;
using Sapper.Models;

namespace Sapper.Controllers
{
    public class GameController : Controller
    {
        private SapperEngine.SapperEngine Game
        {
            get { return (SapperEngine.SapperEngine) Session["game"]; }
            set { Session.Add("game", value); }
        }

        private GameSettings Settings
        {
            get { return (GameSettings) Session["settings"]; }
            set { Session.Add("settings", value); }
        }


        //
        // GET: /Game/

        public ActionResult Index()
        {
            if (Game == null)
                return RedirectToAction("Create");

            return View();
        }

        //
        // GET: /Game/Create

        public ActionResult Create()
        {
            return View(new GameSettings());
        }

        public ActionResult Reload()
        {
            if (Settings == null)
                return RedirectToAction("Create");

            var settingEndTime = new DateTime(2050, 1, 1);
            if (Settings.IsTimeLimit)
                settingEndTime = DateTime.Now + Settings.TimeLimit;

            Game = new SapperEngine.SapperEngine(
                Settings.Width,
                Settings.Height,
                Settings.MineNumber,
                settingEndTime,
                Settings.SelectedFigure);

            return RedirectToAction("Index");
        }

        //
        // POST: /Game/Create

        [HttpPost]
        public ActionResult Create(GameSettings settings)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(settings);

                Settings = settings;

                return RedirectToAction("Reload");
            }
            catch
            {
                return View(settings);
            }
        }

        public ActionResult Close()
        {
            Game = null;
            return RedirectToAction("Create");
        }

        [HttpPost]
        public void UserAction(UserActionModel userAction)
        {
            if (Game.State != SapperEngine.GameState.InGame)
            {
                GameState();
                return;
            }

            if (userAction.Action == UserActionModel.ActionEnum.OpenCell)
                Game.OpenCell(userAction.Column, userAction.Row);

            if (userAction.Action == UserActionModel.ActionEnum.OpenCellAround)
                Game.OpenCellsAround(userAction.Column, userAction.Row);

            if (userAction.Action == UserActionModel.ActionEnum.ToggleFlag)
                Game.ToggleFlag(userAction.Column, userAction.Row);

            GameState();
        }

        [HttpPost]
        public void GameState()
        {
            if (Game.State == SapperEngine.GameState.GameOver)
                Game.OpenAllMines();

            SapperEngineModel model = Game.GetModel();
            string jsonObject = JsonConvert.SerializeObject(model);
            Response.Write(jsonObject);
        }
    }
}

Sapper/Sapper/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Sapper.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

Sapper/Sapper/Views/Game/Create.cshtml
@model Sapper.Models.GameSettings

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create new game</h2>
<div>
    <a href="@Url.Action("Index", "Home")">Back</a>
    <br />
    <br />
    @using (Html.BeginForm("Create", "Game", FormMethod.Post))
    {
        <div>
            @Html.ValidationMessage("Error")
        </div>
        <label>Width (3-50)</label>
        <div>
            @Html.TextBox("Width", Model.Width)
        </div>
        <label>Height (3-50)</label>
        <div>
            @Html.TextBox("Height", Model.Height)
        </div>
        <label>Mine Number (>0)</label>
        <div>
            @Html.TextBox("MineNumber", Model.MineNumber)
        </div>
        <label>Time Limit (00:00:00 means unlimited time)</label>
        <div>
            @Html.TextBox("TimeLimit", Model.TimeLimit)
        </div>
        <label>Figure</label>
        <div>
            @Html.DropDownListFor(m => m.SelectedFigure, Model.FigureList)
        </div>
        <br />
        <div>
            <input type="submit" value="Create"/>
        </div>
    }
</div>

Sapper/Sapper/Views/Game/Game.cshtml
<div class="sapper-content">
    <div class="sapper-message">
    </div>
    <div class="sapper-time">
    </div>
    <div class="sapper-area">
    </div>
</div>
@Scripts.Render("~/bundles/sapper-modul")

Sapper/Sapper/Views/Game/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sapper</h2>
<div>
    <a href="@Url.Action("Close", "Game")">Back</a><br />
    <a href="@Url.Action("Reload", "Game")">Reload</a>
    <h4>Instruction</h4>
    <ul>
        <li>Left Mouse Click (LMC) - open a cell.</li>
        <li>Ctrl+LMC - toggle a flag.</li>
        <li>Alt+LMC - open 8 cells around except flagged.</li>
    </ul>
    <br />
    @{ Html.RenderPartial("Game"); }
</div>

Sapper/Sapper/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>About</h2>
<div>
    <a href="@Url.Action("Index", "Home")">Back</a>
    <h3>Technical Requirements</h3>
    <p>Написать сапер на ASP MVC.</p>
    <p>Функциональность:</p>
    <ul>
        <li>
            Генерация карты(кол-во клеток, кол-во мин)
        </li>
        <li>
            Режима игры: ограниченное время, неограниченное время
        </li>
    </ul>
    <h3>References</h3>
    <ul>
        <li>
            <a href="http://habrahabr.ru/post/176021/">ASP.NET MVC Урок 4. Routing</a>
        </li>
        <li>
            <a href="http://habrahabr.ru/post/176023/">ASP.NET MVC Урок 5. Создание записи в БД</a>
        </li>
        <li>
            <a href="http://habrahabr.ru/post/176053/">ASP.NET MVC Урок 7. Bootstrap, jQuery, Ajax</a>
        </li>
        <li>
            <a href="http://stackoverflow.com/questions/1787939/check-time-difference-in-javascript">Check time difference in Javascript</a>
        </li>
        <li>
            <a href="http://stackoverflow.com/questions/1038746/equivalent-of-string-format-in-jquery">Equivalent of String.format in JQuery</a>
        </li>
    </ul>
</div>

Sapper/Sapper/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Sapper Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sapper</h2>
<div>
    <a href="@Url.Action("Index", "Game")">Start new game</a><br />
    <a href="@Url.Action("About", "Home")">About</a>
</div>

Sapper/Sapper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/some-script")
    </head>
    <body>
        @RenderBody()
        @RenderSection("scripts", false)
    </body>
</html>